# Generated by Django 4.0.6 on 2022-07-08 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='clients',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clients',
            name='project_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mains.projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='assign_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='assign_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
