# Generated by Django 4.0.6 on 2022-07-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0002_remove_projects_created_by_alter_clients_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='project_list',
        ),
        migrations.AddField(
            model_name='projects',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mains.clients'),
        ),
    ]
