# Generated by Django 4.0.6 on 2022-07-08 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mains', '0003_remove_clients_project_list_projects_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='assign_to',
            field=models.ManyToManyField(blank=True, related_name='assign_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
