# Generated by Django 4.0.6 on 2022-07-08 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0004_alter_projects_assign_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='mains.clients'),
        ),
    ]
